/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'ApolloFirmware' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "apollo3.h"

/* Keil::Compiler&ARM Compiler:I/O:STDERR&ITM@1.2.0 */
#define RTE_Compiler_IO_STDERR          /* Compiler I/O: STDERR */
#define RTE_Compiler_IO_STDERR_ITM      /* Compiler I/O: STDERR ITM */
/* Keil::Compiler&ARM Compiler:I/O:STDIN&ITM@1.2.0 */
#define RTE_Compiler_IO_STDIN           /* Compiler I/O: STDIN */
#define RTE_Compiler_IO_STDIN_ITM       /* Compiler I/O: STDIN ITM */
/* Keil::Compiler&ARM Compiler:I/O:STDOUT&ITM@1.2.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
#define RTE_Compiler_IO_STDOUT_ITM      /* Compiler I/O: STDOUT ITM */
/* Keil::Compiler&ARM Compiler:I/O:TTY&Breakpoint@1.2.0 */
#define RTE_Compiler_IO_TTY             /* Compiler I/O: TTY */
#define RTE_Compiler_IO_TTY_BKPT        /* Compiler I/O: TTY Breakpoint */


#endif /* RTE_COMPONENTS_H */
